//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoticeBoard.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;

    public partial class Notice
    {
        public string Title { get; set; }
        public string Headlines { get; set; }
        [DisplayName("Session")]
        public string SessionID { get; set; }
        [DisplayName("Department")]
        public string DepartmentID { get; set; }
        [DisplayName("Upload File")]
        public string ImagePath { get; set; }
    
        public HttpPostedFileBase ImageFile { get; set; }
        public virtual Department Department { get; set; }
    }
}
